credentials:
  batch:
    account: BATCH_ACCOUNT_NAME
    account_key: BATCH_ACCOUNT_KEY
    account_service_url: BATCH_ACCOUNT_URL
  storage:
    mystorageaccount:
      account: STORAGE_ACCOUNT_NAME
      account_key: STORAGE_ACCOUNT_KEY
      endpoint: core.windows.net